---

- name: install required debian packages
  apt:
    pkg:
      - dconf-cli

- name: dconf profile directory
  file:
    path: /etc/dconf/profile
    state: directory

- name: dconf profile dbs setting
  copy:
    src: profile/user
    dest: /etc/dconf/profile/user
  notify: dconf update

- name: dconf local db directory
  file:
    path: /etc/dconf/db/local.d/
    state: directory

- name: dconf settings
  template:
    src: settings.j2
    dest: /etc/dconf/db/local.d/{{dconf_id}}
  notify: dconf update

- name: dconf locks directory
  file:
    path: /etc/dconf/db/local.d/locks
    state: directory

- name: dconf locks
  template:
    src: locks.j2
    dest: /etc/dconf/db/local.d/locks/{{dconf_id}}
  when: dconf_lock_paths is defined
  notify: dconf update
