---

- name: make sure debian ansible package is absent
  apt:
    pkg: ansible
    state: absent

- name: cleanup ara pip package
  pip:
    name: ara
    state: absent
    executable: pip3
  when: not ansible_use_ara

- name: cleanup mitogen pip package
  pip:
    name: mitogen
    state: absent
    executable: pip3
  when: not ansible_use_mitogen
