---

- name: make sure debian ansible package is absent
  apt:
    pkg: ansible
    state: absent

- name: cleanup ansible lxc_ssh plugin
  file:
    path: /usr/share/ansible/plugins/connection/lxc_ssh
    state: absent

- name: cleanup ansible ovh module
  file:
    path: /usr/share/ansible/modules/ovh
    state: absent
  when: not ansible_with_ovh_module

- name: cleanup ara pip package
  pip:
    name: ara
    state: absent
    executable: pip3
  when: not ansible_use_ara

- name: cleanup mitogen pip package
  pip:
    name: mitogen
    state: absent
    executable: pip3
  when: not ansible_use_mitogen

- name: cleanup ansible ovh module
  file:
    path: /usr/share/ansible/modules/ovh/
    state: absent

- name: make sure old python2 ansible pip package is absent
  pip:
    name: ansible
    state: absent
    executable: pip2

- name: make sure old python2 ara pip package is absent
  pip:
    name: ara
    state: absent
    executable: pip2

- name: make sure old python2 ovh client package is absent
  pip:
    name: ovh
    executable: pip2
    state: absent

- name: make sure old python2 mitogen pip package is absent
  pip:
    name: mitogen
    state: absent
    executable: pip2
