---

- name: debian base packages
  apt:
    pkg: "{{ debian_base_packages }}"
  when: debian_base_packages is defined

- name: debian boot packages
  apt:
    pkg: "{{ debian_boot_packages }}"
  when: debian_boot_packages is defined

- name: debian common packages
  apt:
    pkg: "{{ debian_common_packages }}"

- name: debian custom packages
  apt:
    pkg: "{{ debian_custom_packages }}"
  when: debian_custom_packages is defined
