---

- name: fish package
  apt:
    pkg: fish

- name: fish config directory
  file:
    path: /etc/fish/conf.d
    state: directory

- name: fish config files
  copy:
    src: fish/global/
    dest: /etc/fish/conf.d/
  with_items:
    - fish_title
    - fish_prompt
    - fish_greeting

- name: fish package
  package:
    name: fish
  when: not root_target_directory is defined

# root user
- name: fish root user config directory
  file:
    path: /root/.config/fish/conf.d/
    state: directory

- name: fish root user config files
  copy:
    src: fish/root/
    dest: /root/.config/fish/conf.d/

- name: fish shell for root user
  user:
    name: root
    shell: /usr/bin/fish
