---

- name: desktop packages
  apt:
    pkg: "{{ desktop_packages }}"

- import_role:
    name: atom_editor

- name: ensure dunst package is absent for nicer notifications
  apt:
    pkg: dunst
    state: absent

- name: xorg touchpad config
  template:
    src: touchpad.conf.j2
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf

- import_tasks: screensaver.yaml
