---

- include_tasks: setup_Debian.yml

- include_tasks: ansible.yaml


- include_tasks: connection_plugin_lxc_ssh.yml
#- include_tasks: ara.yml

- include_tasks: ovh_module.yml

- name: ansible etc directory
  file:
    path: /etc/ansible
    state: directory

- name: ansible config
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg

- include_tasks: roles.yml
