---

- include_tasks: setup_Debian.yaml

- include_tasks: ansible.yaml

- include_tasks: mitogen.yaml
  when: ansible_use_mitogen

- include_tasks: ara.yaml
  when: ansible_use_ara

- import_tasks: config.yaml

- import_tasks: cleanup.yaml
