---

# user setup
- import_role:
    name: root_user
- import_role:
    name: users
- import_role:
    name: fish

# system setup
- import_role:
    name: hostname
  when:
    - not ansible_bender is defined
    - not container_type | default('') == 'podman'
- import_role:
    name: locales
- import_role:
    name: timezone
  when: not ansible_bender is defined
- import_role:
    name: keyboard_configuration
  when: not ansible_bender is defined

# packages setup
- import_role:
    name: debian_repos
  when:
    - ansible_distribution == "Debian"
    - not ansible_lsb.id is defined or ansible_lsb.id != "Raspbian"
- import_role:
    name: debian_packages
  when: ansible_distribution == "Debian"
- import_role:
    name: system_upgrade
- import_role:
    name: unattended-upgrades
  when: not ansible_bender is defined
