---

- include: setup_Debian.yml

- include: ara.yml

- include: connection_plugin_lxc_ssh.yml

- include: ovh_module.yml

- name: ansible config
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg

- include: roles.yml
