---

- name: update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: upgrade all packages
  apt:
    upgrade: dist

- name: unattended-upgrades
  apt:
    name: unattended-upgrades
  when:
    - unattended_upgrades
    - not ansible_bender is defined
