---

- name: make sure no other display managers are installed
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - slim
    - gdm3
    - kdm
    - sddm

- name: install packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - xserver-xorg
    - xserver-xorg-video-all
    - xserver-xorg-input-all
    - x11-xserver-utils
    - lightdm
    - lightdm-gtk-greeter
    - onboard
    - yad
    - xbindkeys
    - feh
  notify: restart lightdm

- include: mainentance.yml
  when: display_manager_state == 'mainentance'

- name: lightdm configuration
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
  notify: restart lightdm

- name: lightdm gtk-greeter configuration
  template:
    src: lightdm-gtk-greeter.conf.j2
    dest: /etc/lightdm/lightdm-gtk-greeter.conf
  notify: restart lightdm

- name: lightdm display setup script
  template:
    src: display-setup.sh.j2
    dest: /etc/lightdm/display-setup.sh
    mode: u=rwx,g=rx,o=rx
  when: display_setup_commands is defined
  notify: restart lightdm

- name: background image directory
  file:
    path: /usr/share/lightdm/background
    state: directory

- name: background image
  copy:
    src: "{{display_manager_background_image}}"
    dest: "/usr/share/lightdm/background/{{display_manager_background_image}}"

- name: lightdm started
  service:
    name: lightdm
    state: started
    enabled: yes

- meta: flush_handlers
