---

- name: mainentance user
  user:
    name: mainentance
    system: yes
    createhome: yes
    home: /var/lib/mainentance
  notify: restart lightdm

- name: mainentance directory
  file:
    path: /usr/local/share/mainentance
    state: directory
  notify: restart lightdm

- name: mainentance xsession desktop
  template:
    src: mainentance.desktop.j2
    dest: /usr/local/share/mainentance/mainentance.desktop
  notify: restart lightdm

- name: mainentance xsession script
  template:
    src: mainentance-xsession.sh.j2
    dest: /usr/local/share/mainentance/xsession
    mode: u=rwx,g=rx,o=rx
  notify: restart lightdm

- name: mainentance xbindkeys
  template:
    src: mainentance.xbindkeys.j2
    dest: /usr/local/share/mainentance/xbindkeys
  notify: restart lightdm
