---

- name: delete depecrated packages
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - slim

- name: install packages
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - xserver-xorg
    - xserver-xorg-video-all
    - xserver-xorg-input-all
    - x11-xserver-utils

- service:
    name: slim
    state: stopped
    enabled: no
