---

- name: signal apt key
  apt_key:
    id: DBA36B5181D0C816F630E889D980A17457F6FB06
    url: https://updates.signal.org/desktop/apt/keys.asc
    keyring: /etc/apt/trusted.gpg.d/signal.gpg

- name: signal apt repo
  apt_repository:
    repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
    filename: signal

- name: signal package
  apt:
    pkg: signal-desktop
