---

- name: ensure resolvconf is installed
  apt:
    pkg: resolvconf

- name: link resolv.conf
  file:
    src: /run/resolvconf/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
