---

- name: root user password
  user:
    name: root
    password: "{{ root_password }}"
  when: root_password is defined

- name: root user ssh key
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_type: ed25519
  when:
    - root_ssh_key
    - not root_target_directory is defined

- name: root user ssh directory
  file:
    path: "{{ root_target_directory | default('') }}/root/.ssh"
    state: directory
  when: root_ssh_authorized_keys is defined

- name: root user ssh authorized keys
  template:
    src: root_user_ssh_authorized_keys.j2
    dest: "{{ root_target_directory | default('') }}/root/.ssh/authorized_keys"
  when: root_ssh_authorized_keys is defined
