---

- name: install packages
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - ansible
    - python-pip
    - ipv6calc
    - uuid
    - git
    - python-jmespath
    # ara required_packages:
    - gcc
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt-dev
    - python-dev
    - python-setuptools
    - python-pymysql
    #- which
