---
# tasks file for youtube-dl
- name: install youtube-dl package
  apt: name=youtube-dl state=latest
- name: download latest youtube-dl
  get_url: url=https://yt-dl.org/downloads/latest/youtube-dl dest=/usr/local/bin/youtube-dl mode=755
