---

- name: desktop packages
  apt:
    pkg: "{{ desktop_packages }}"

- name: ensure dunst package is absent for nicer notifications
  apt:
    pkg: dunst
    state: absent


- name: unclutter default config
  template:
    src: unclutter.default.j2
    dest: /etc/default/unclutter


